### ISSUE TITLE
Đề xuất tính năng cho dự án trong product backlog

### ISSUE THREAD

**Issue by tungn2002** [tungn2002/QuanLyNhanSu#1]

**Comment by Pham-Khanh-Long** [comment]
[Các tính năng, chức năng của quản lý nhân sự mềm .docx](https://github.com/tungn2002/QuanLyNhanSu/files/7229857/Cac.tinh.nang.ch.c.nang.c.a.qu.n.ly.nhan.s.m.m.docx)

**Comment by KhanhNamNguyen** [comment]
https://sg.docworkspace.com/d/sINfa9uSJAcK3vYoG

**Comment by minhnam9apc** [comment]
https://wru-my.sharepoint.com/personal/2051060629_e_tlu_edu_vn/_layouts/15/doc.aspx?sourcedoc={461ac6fe-e64a-4861-bfbf-c29b516b45b9}&action=edit

**Comment by tungn2002** [comment]
Tối nay phải hoàn thành cv : Đây là file tôi lựa chọn những tính năng mà nhóm mình có thể phát triển được
+vào phần project chọn nv 2 lấy link điền(theo cấu trúc user story ), mỗi tính năng ghi tầm 2-3 dòng.
+độ ưu tiên đã sắp xếp từ trên xuống dưới
+tên của ai được viết trên đầu mỗi tính năng thì người đó sẽ điền tính năng đấy vào
+cột ID thì mỗi người 1 số @@ đừng để 1 người nhiều id

Link các tính năng: https://docs.google.com/document/d/1LUEYxinwYzPCQpdXxzrL-CuKrmdtrNjH/edit?usp=sharing&ouid=118402615077717564281&rtpof=true&sd=true
