### ISSUE TITLE
Đặc tả yêu cầu

### ISSUE THREAD

**Issue by tungn2002** [tungn2002/QuanLyNhanSu#4]

**Comment by minhnam9apc** [comment]
https://wru-my.sharepoint.com/:w:/g/personal/2051060629_e_tlu_edu_vn/EfhJgGEn1iZMsM4H61wyXnEBAI7rYZyn2RHbdLSC-N6Prw?e=thXHso

**Comment by Pham-Khanh-Long** [comment]
[Uploading Biểu đồ.docx…]()

**Comment by Pham-Khanh-Long** [comment]
[Uploading Biểu đồ.docx…]()

**Comment by Pham-Khanh-Long** [comment]
[Biểu đồ.docx](https://github.com/tungn2002/QuanLyNhanSu/files/7272864/Bi.u.d.docx)

**Comment by KhanhNamNguyen** [comment]
https://sg.docworkspace.com/d/sIPja9uSJAZG15YoG

**Comment by Pham-Khanh-Long** [comment]
[Biểu đồ.docx](https://github.com/tungn2002/QuanLyNhanSu/files/7303740/Bi.u.d.docx)

**Comment by KhanhNamNguyen** [comment]
https://sg.docworkspace.com/d/sINna9uSJAZj4-4oG

**Comment by minhnam9apc** [comment]
https://wru-my.sharepoint.com/:w:/g/personal/2051060629_e_tlu_edu_vn/EfhJgGEn1iZMsM4H61wyXnEB4D4cGptN2kYOfOmkzNyp9g?e=aaOF8b%5D

**Comment by KhanhNamNguyen** [comment]
https://sg.docworkspace.com/d/sIEfa9uSJAYmrgYsG

**Comment by Pham-Khanh-Long** [comment]
[Biều đồ sprint1.docx](https://github.com/tungn2002/QuanLyNhanSu/files/7312041/Bi.u.d.sprint1.docx)
