### ISSUE TITLE
Phân tích thiết kế

### ISSUE THREAD

**Issue by tungn2002** [tungn2002/QuanLyNhanSu#5]

**Comment by tungn2002** [comment]
[Giao dien.docx](https://github.com/tungn2002/QuanLyNhanSu/files/7312816/Giao.dien.docx)

**Comment by minhnam9apc** [comment]
https://docs.google.com/document/d/1pWAU6ITwHXfnMwKSonOPmjly0IGxJXxHdTyW6cUsGQ8/edit
